name: 'taxi_emissions_project'
version: '1.0.0'
config-version: 2

profile: 'taxi_emissions_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  taxi_emissions_project:
    +materialized: table